name: Zip AI API datapack
on: push
jobs:
  packsquash:
    name: Procces
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Pack squash
      uses: ComunidadAylas/PackSquash-action@v4
      with:
        packsquash_version: latest
        options:
          pack_directory = './AIAPI-1.20.1'
          zip_spec_conformance_level = 'high'